### ISSUE TITLE
SplashActivity界面的按钮自动触发了点击事件

### ISSUE THREAD

**Issue by imswy** [suming77/SumTea_Android#10]
SplashActivity的倒计时功能没有效果,通过打断点发现

```kotlin
mBinding.tvSkip.onClick {
            MainServiceProvider.toMain(this)
        }
```
在没有点击的情况下被触发了

**Comment by suming77** [comment]
1.倒计时没结束，点击【跳过】会进入主界面
2.倒计时结束，自动进入主界面

**Comment by imswy** [comment]
未点击【跳过】,直接就触发 MainServiceProvider.toMain(this)方法了
手机是红米的,我用三星的试了一下没这个问题,多半是MIUI的Bug
